### ISSUE TITLE
Could it work without composer ?

### ISSUE THREAD

**Issue by carry0987** [lutsen/updrive#1]
Just use php

**Comment by lutsen** [comment]
@carry0987 Yes it could, but Composer just makes it so much easier to manage dependencies. And once you give it a try, you'll find out it really isn't that hard. Don't be afraid of the commandline :-)

[Start with Composer](https://getcomposer.org/doc/00-intro.md)

(Composer is also intergrated in [Netbeans](https://netbeans.org/) and [Eclipse](https://eclipse.org/pdt/) but I never tried that myself)

**Comment by carry0987** [comment]
OK !
I will try it!!
